### PR TITLE
Allow call recording for Australia

### PR DESCRIPTION
**Pull request by sergethedev17**
All states and territories permit recording one's phone calls, subject to certain restrictions.

### CODE REVIEW

**Comment by roshavagarga** [comment]
Call recording in Australia suffers from the same problems as call recording in the USA:
Neither can be enabled, due to the countries not having a unified stance. Some states in the USA allow it, others do not without consent from both parties.

Australia has differing laws on this, based on which territory you are in. Some mark it as a criminal offense, others do not. Since call recording is enabled or disabled based on MCC codes (SIM Card/Network identifiers which can't differ between states) there is no feasible way of enabling call recording.

If you can present proof that there is a legal precedent and/or national law that trumps territorial laws, then this could be enabled.

**Comment by sergeroz** [comment]
Proposed commit includes legislative references from each jurisdiction. All states and territories allow recording, subject to some restrictions. Recording should be enabled for Australia.

**Comment by roshavagarga** [comment]
After carefully going through the linked documents, most territories and states offer some reasonable situations in which a person would not be penalized for recording a conversation he or she is a part of. 

The exception that I have found among these is the State of Victoria, which obviously does not allow the recording of a conversation by a party of that conversation, in any situation. It is clearly stated that this can be done with the consent of a party, but by a law enforcement officer, hence it would be illegal in any other situation.

Due to the use of MCC codes to enforce the enabled or disabled state, until the State of Victoria has a change in legislation, it will not be possible to enable call recording for Australia.

**Comment by ItzLevvie** [comment]
Hey there, @sergethedev17!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by roshavagarga** [comment]
Changes have been merged based on this suggestion, but with a disabled state. This pull request should be considered closed until the law changes in certain Australian territories.

**Pull request closed without merging**
