### PR TITLE
Allow call recording for Israel

### PR DESCRIPTION
**Pull request by NeatNit**
Not entirely sure if I did this right. I've probably made the comment too verbose, looking at other countries, but I'm not really sure what source to use: an article, which isn't guaranteed to be correct? [A copy/mirror of] the eavesdropping law as written, which simply *doesn't apply* to recording your own conversations? AFAIK there is no "legal precedent" to speak of (i.e. a court case that had a verdict), and looking at some of the other countries, some of them seem to link to law sources while still incorrectly calling it "legal precedent".

### CODE REVIEW

**Comment by Jprimero15** [comment]
Submit to gerrit..

**Comment by NeatNit** [comment]
I couldn't figure out how.

**Comment by roshavagarga** [comment]
@NeatNit I am adding this to an upcoming commit for multiple MCC codes, as is, based on both of your proposed changes. I have added you to said change, which you can see through gerrit or https://http://review.lineageos.org

**Comment by roshavagarga** [comment]
@NeatNit I have added your gerrit account to the commit, you should be able to see it in the main menu. You can take a look at the file, make sure everything is okay. Besides that, if you know any languages of other countries that are not currently handled by the system, you can send me information about them, so that I may add them as enabled/disabled for call recording.

**Comment by NeatNit** [comment]
Yes, I saw it, and I saw that you added my file exactly as is which is fine by me. I don't know about any country other than my own :)

**Comment by roshavagarga** [comment]
Great! Well, besides those I still have some research to do on a few big countries + a few European countries, so that I can properly add those. I also have to make changes to all of the current XML files, in order to change the 'standard' of writing. As you noted, 'legal precedent' is not the most correct term here (plus tidying the everything for readability).

This will take at least a couple more days, after that it will all depend on the LOS developers - I will add people, who should theoretically review the code and changes, verify whether there are any problems and then it gets merged. I myself am not technically adept, so I create the changes via the website, hence I can't do any of the above. Worst case scenario, it'll be in the code within 30 days, best case scenario I'd say 7-10 days.

**Comment by roshavagarga** [comment]
If you can get your hands on one, I'd highly recommend grabbing a BQ X Pro (codename bardockpro), or X2 Pro (codename zangyapro). Wonderful little mid-tier phones with a solid LOS dev team behind them. I'm a proud owner of a bardock myself :)

**Comment by NeatNit** [comment]
Thanks for the recommendation! But I've made a decision long ago that my next phone will have an OLED screen, and it seems like those don't... Looking at some Xiaomi phones that a shop I trust recommended, seems none of them have LineageOS (too new?) but if their stock isn't garbage I'm not too worried.

This isn't really the right place for this conversation though...

**Comment by ItzLevvie** [comment]
Hey there, @NeatNit!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by roshavagarga** [comment]
Changes have been made accordingly based on the suggested input. This pull request should be considered complete and thus - closed.

**Pull request closed without merging**
